Improve test script

diff --git a/hooks/test b/hooks/test
--- a/hooks/test
+++ b/hooks/test
@@ -3,6 +3,7 @@
 . ./hooks/env
 
 JQ="docker run --rm -i articulate/jq"
+CONSUL_COUNT=${1:-3}
 
 function retry {
   local retry_max=$1
@@ -32,7 +33,11 @@ function finish {
 trap finish EXIT
 
 function passing_service {
+  echo -n "Checking if service $1 is passing ... "
   docker run --rm --network container:consultest_consul_1 appropriate/curl -s http://localhost:8500/v1/health/state/passing | grep -q "ServiceName.*$1"
+  RESULT=$?
+  [ $RESULT = 0 ] && echo "PASS" || echo "FAIL"
+  return $RESULT
 }
 
 function until_started {
@@ -43,21 +48,22 @@ function until_started {
 }
 
 function test_suite {
-  retry 30 docker exec consultest_consul_1 curl -s --fail http://localhost:8500/v1/health/state/passing
-  retry 30 docker exec consultest_consul_2 curl -s --fail http://localhost:8500/v1/health/state/passing
-  retry 30 docker exec consultest_consul_3 curl -s --fail http://localhost:8500/v1/health/state/passing
+  for I in $(seq 1 ${CONSUL_COUNT}); do
+    retry 30 docker exec consultest_consul_${I} curl -sf http://localhost:8500/v1/health/state/passing
+    echo
+  done
 
   retry 15 passing_service consul
 
-  retry 5 docker run --rm --network container:consultest_consul_1 appropriate/curl -s -o /dev/null http://localhost:9090/metrics
+  retry 5 docker run --rm --network container:consultest_consul_1 appropriate/curl -sf -o /dev/null http://localhost:9090/metrics
   retry 5 passing_service containerpilot
 
-  retry 5 docker run --rm --network container:consultest_consul_1 appropriate/curl -s -o /dev/null http://localhost:9100/metrics
+  retry 5 docker run --rm --network container:consultest_consul_1 appropriate/curl -sf -o /dev/null http://localhost:9100/metrics
   retry 5 passing_service node-exporter
 }
 
 export IMAGE_NAME
-docker-compose -p consultest -f hooks/docker-compose.yml up -d --scale consul=3
+docker-compose -p consultest -f hooks/docker-compose.yml up -d --scale consul=${CONSUL_COUNT}
 until_started
 
 test_suite
