Add advertise CIDR block variables

diff --git a/hooks/test b/hooks/test
--- a/hooks/test
+++ b/hooks/test
@@ -1,4 +1,4 @@
-#!/bin/bash -xe
+#!/bin/bash -e
 
 . ./hooks/env
 
@@ -23,9 +23,11 @@ function retry {
 }
 
 function finish {
+  RESULT=$?
   docker-compose -p consultest -f hooks/docker-compose.yml logs
   docker-compose -p consultest -f hooks/docker-compose.yml exec consul consul members || true
   docker-compose -p consultest -f hooks/docker-compose.yml down
+  [ $RESULT = 0 ] && echo "PASS" || echo "FAIL"
 }
 trap finish EXIT
 
